import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // TypeScript 관련 규칙 완전 비활성화
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      
      // React 관련 규칙 완전 비활성화
      'react/no-unescaped-entities': 'off',
      'react/no-unknown-property': 'off',
      'react/no-array-index-key': 'off',
      'react/display-name': 'off',
      'react/no-children-prop': 'off',
      'react/jsx-key': 'off',
      'react/jsx-no-target-blank': 'off',
      'react/jsx-no-duplicate-props': 'off',
      'react/jsx-no-undef': 'off',
      'react/jsx-uses-react': 'off',
      'react/jsx-uses-vars': 'off',
      'react/no-danger': 'off',
      'react/no-deprecated': 'off',
      'react/no-direct-mutation-state': 'off',
      'react/no-find-dom-node': 'off',
      'react/no-is-mounted': 'off',
      'react/no-render-return-value': 'off',
      'react/no-string-refs': 'off',
      'react/no-unescaped-entities': 'off',
      'react/no-unknown-property': 'off',
      'react/prop-types': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/require-render-return': 'off',
      'react/self-closing-comp': 'off',
      'react/sort-comp': 'off',
      'react/sort-prop-types': 'off',
      'react/style-prop-object': 'off',
      'react/void-dom-elements-no-children': 'off',
      
      // Next.js 관련 규칙 완전 비활성화
      '@next/next/no-img-element': 'off',
      '@next/next/no-html-link-for-pages': 'off',
      '@next/next/no-sync-scripts': 'off',
      '@next/next/no-page-custom-font': 'off',
      '@next/next/no-css-tags': 'off',
      '@next/next/no-head-element': 'off',
      '@next/next/no-title-in-document-head': 'off',
      '@next/next/no-typos': 'off',
      '@next/next/no-unwanted-polyfillio': 'off',
      '@next/next/no-before-interactive-script-outside-document': 'off',
      '@next/next/no-duplicate-head': 'off',
      '@next/next/no-script-component-in-head': 'off',
      '@next/next/no-styled-jsx-in-document': 'off',
      '@next/next/no-google-font-display': 'off',
      '@next/next/no-page-custom-font': 'off',
      '@next/next/no-sync-scripts': 'off',
      '@next/next/no-unwanted-polyfillio': 'off',
      
      // 일반 JavaScript 규칙 완전 비활성화
      'no-unused-vars': 'off',
      'no-undef': 'off',
      'no-console': 'off',
      'no-debugger': 'off',
      'no-alert': 'off',
      'no-var': 'off',
      'prefer-const': 'off',
      'no-constant-condition': 'off',
      'no-empty': 'off',
      'no-extra-boolean-cast': 'off',
      'no-extra-semi': 'off',
      'no-func-assign': 'off',
      'no-inner-declarations': 'off',
      'no-irregular-whitespace': 'off',
      'no-obj-calls': 'off',
      'no-regex-spaces': 'off',
      'no-sparse-arrays': 'off',
      'no-unexpected-multiline': 'off',
      'no-unreachable': 'off',
      'use-isnan': 'off',
      'valid-jsdoc': 'off',
      'valid-typeof': 'off',
      
      // 기타 규칙 완전 비활성화
      'prefer-arrow-callback': 'off',
      'arrow-spacing': 'off',
      'block-spacing': 'off',
      'brace-style': 'off',
      'camelcase': 'off',
      'comma-dangle': 'off',
      'comma-spacing': 'off',
      'comma-style': 'off',
      'computed-property-spacing': 'off',
      'consistent-this': 'off',
      'eol-last': 'off',
      'func-call-spacing': 'off',
      'func-name-matching': 'off',
      'func-names': 'off',
      'func-style': 'off',
      'id-blacklist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'indent': 'off',
      'jsx-quotes': 'off',
      'key-spacing': 'off',
      'keyword-spacing': 'off',
      'linebreak-style': 'off',
      'lines-around-comment': 'off',
      'max-depth': 'off',
      'max-len': 'off',
      'max-lines': 'off',
      'max-nested-callbacks': 'off',
      'max-params': 'off',
      'max-statements': 'off',
      'max-statements-per-line': 'off',
      'multiline-ternary': 'off',
      'new-cap': 'off',
      'new-parens': 'off',
      'newline-after-var': 'off',
      'newline-before-return': 'off',
      'newline-per-chained-call': 'off',
      'no-array-constructor': 'off',
      'no-bitwise': 'off',
      'no-continue': 'off',
      'no-inline-comments': 'off',
      'no-lonely-if': 'off',
      'no-mixed-operators': 'off',
      'no-mixed-spaces-and-tabs': 'off',
      'no-multiple-empty-lines': 'off',
      'no-negated-condition': 'off',
      'no-nested-ternary': 'off',
      'no-new-object': 'off',
      'no-plusplus': 'off',
      'no-restricted-syntax': 'off',
      'no-tabs': 'off',
      'no-ternary': 'off',
      'no-trailing-spaces': 'off',
      'no-underscore-dangle': 'off',
      'no-unneeded-ternary': 'off',
      'no-whitespace-before-property': 'off',
      'object-curly-newline': 'off',
      'object-curly-spacing': 'off',
      'object-property-newline': 'off',
      'one-var': 'off',
      'one-var-declaration-per-line': 'off',
      'operator-assignment': 'off',
      'operator-linebreak': 'off',
      'padded-blocks': 'off',
      'quote-props': 'off',
      'quotes': 'off',
      'require-jsdoc': 'off',
      'semi': 'off',
      'semi-spacing': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
      'space-before-blocks': 'off',
      'space-before-function-paren': 'off',
      'space-in-parens': 'off',
      'space-infix-ops': 'off',
      'space-unary-ops': 'off',
      'spaced-comment': 'off',
      'template-tag-spacing': 'off',
      'unicode-bom': 'off',
      'wrap-regex': 'off',
    },
  },
];

export default eslintConfig;
