'use client';

import React, { useState } from 'react';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { 
  TrendingUp, 
  TrendingDown, 
  ArrowRight, 
  Target, 
  Lightbulb, 
  Users, 
  BarChart3,
  CheckCircle2,
  AlertTriangle,
  Star,
  Award,
  Zap,
  Clock,
  Download,
  Share2
} from 'lucide-react';

interface McKinseyReportProps {
  data: {
    companyName: string;
    overallScore: number;
    grade: string;
    categoryScores: Record<string, number>;
    recommendations: string[];
    strengths: string[];
    improvements: string[];
    roadmap: {
      phase1: string;
      phase2: string;
      phase3: string;
    };
  };
}

export const PremiumMcKinseyReport: React.FC<McKinseyReportProps> = ({ data }) => {
  const [activeSection, setActiveSection] = useState('executive-summary');

  // 등급별 색상 및 스타일
  const getGradeStyle = (grade: string) => {
    switch(grade) {
      case 'S': return { bg: 'bg-gradient-to-br from-purple-600 to-purple-800', text: 'text-white', accent: 'border-purple-500' };
      case 'A': return { bg: 'bg-gradient-to-br from-blue-600 to-blue-800', text: 'text-white', accent: 'border-blue-500' };
      case 'B': return { bg: 'bg-gradient-to-br from-emerald-600 to-emerald-800', text: 'text-white', accent: 'border-emerald-500' };
      case 'C': return { bg: 'bg-gradient-to-br from-amber-600 to-amber-800', text: 'text-white', accent: 'border-amber-500' };
      case 'D': return { bg: 'bg-gradient-to-br from-orange-600 to-orange-800', text: 'text-white', accent: 'border-orange-500' };
      default: return { bg: 'bg-gradient-to-br from-gray-600 to-gray-800', text: 'text-white', accent: 'border-gray-500' };
    }
  };

  const gradeStyle = getGradeStyle(data.grade);

  // 카테고리 아이콘 매핑
  const categoryIcons = {
    leadership: <Users className="w-5 h-5" />,
    infrastructure: <BarChart3 className="w-5 h-5" />,
    employeeCapability: <Target className="w-5 h-5" />,
    culture: <Star className="w-5 h-5" />,
    practicalApplication: <Zap className="w-5 h-5" />,
    dataCapability: <TrendingUp className="w-5 h-5" />
  };

  const categoryNames = {
    leadership: '경영진 리더십',
    infrastructure: 'AI 인프라',
    employeeCapability: '직원 역량',
    culture: '조직 문화',
    practicalApplication: '실무 적용',
    dataCapability: '데이터 역량'
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100">
      {/* 프리미엄 헤더 */}
      <div className="relative overflow-hidden bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900">
        {/* 백그라운드 패턴 */}
        <div className="absolute inset-0 opacity-10">
          <div className="absolute inset-0" style={{
            backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.1'%3E%3Ccircle cx='30' cy='30' r='2'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`
          }} />
        </div>
        
        <div className="relative max-w-7xl mx-auto px-6 py-16">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-6">
              {/* AICAMP 로고 영역 */}
              <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-4 border border-white/20">
                <div className="w-12 h-12 bg-gradient-to-br from-blue-400 to-purple-600 rounded-xl flex items-center justify-center">
                  <Award className="w-6 h-6 text-white" />
                </div>
              </div>
              
              <div>
                <div className="flex items-center space-x-3 mb-2">
                  <h1 className="text-3xl font-bold text-white">AI 역량진단 보고서</h1>
                  <Badge className="bg-gradient-to-r from-blue-500 to-purple-600 text-white border-0">
                    McKinsey Style
                  </Badge>
                </div>
                <p className="text-xl text-slate-300">{data.companyName}</p>
                <p className="text-sm text-slate-400 mt-1">
                  Generated by AICAMP • {new Date().toLocaleDateString('ko-KR', { 
                    year: 'numeric', 
                    month: 'long', 
                    day: 'numeric' 
                  })}
                </p>
              </div>
            </div>

            {/* 등급 표시 */}
            <div className="text-center">
              <div className={`w-24 h-24 rounded-full ${gradeStyle.bg} flex items-center justify-center shadow-2xl border-4 border-white/20`}>
                <span className="text-4xl font-bold text-white">{data.grade}</span>
              </div>
              <p className="text-white mt-3 font-medium">종합 등급</p>
              <p className="text-slate-300 text-sm">{data.overallScore}점 / 100점</p>
            </div>
          </div>
        </div>
      </div>

      {/* 네비게이션 */}
      <div className="sticky top-0 z-50 bg-white/95 backdrop-blur-sm border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-6">
          <nav className="flex space-x-8 py-4">
            {[
              { id: 'executive-summary', label: '경영진 요약', icon: <Award className="w-4 h-4" /> },
              { id: 'detailed-analysis', label: '상세 분석', icon: <BarChart3 className="w-4 h-4" /> },
              { id: 'strategic-recommendations', label: '전략 제안', icon: <Lightbulb className="w-4 h-4" /> },
              { id: 'implementation-roadmap', label: '실행 로드맵', icon: <Clock className="w-4 h-4" /> }
            ].map((section) => (
              <button
                key={section.id}
                onClick={() => setActiveSection(section.id)}
                className={`flex items-center space-x-2 px-4 py-2 rounded-lg transition-all duration-200 ${
                  activeSection === section.id 
                    ? 'bg-blue-600 text-white shadow-lg' 
                    : 'text-slate-600 hover:bg-slate-100'
                }`}
              >
                {section.icon}
                <span className="font-medium">{section.label}</span>
              </button>
            ))}
          </nav>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-12">
        {/* Executive Summary */}
        {activeSection === 'executive-summary' && (
          <div className="space-y-8">
            {/* Key Insights */}
            <Card className="border-0 shadow-xl bg-gradient-to-br from-white to-slate-50">
              <CardHeader className="pb-8">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
                    <TrendingUp className="w-5 h-5 text-white" />
                  </div>
                  <h2 className="text-2xl font-bold text-slate-800">핵심 인사이트</h2>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                  {/* 현재 위치 */}
                  <div className="text-center p-6 bg-white rounded-2xl shadow-lg border border-slate-100">
                    <div className="w-16 h-16 bg-gradient-to-br from-emerald-400 to-emerald-600 rounded-full flex items-center justify-center mx-auto mb-4">
                      <Target className="w-8 h-8 text-white" />
                    </div>
                    <h3 className="text-lg font-bold text-slate-800 mb-2">현재 수준</h3>
                    <p className="text-3xl font-bold text-emerald-600 mb-2">{data.overallScore}점</p>
                    <p className="text-sm text-slate-600">업계 평균 대비 상위 15%</p>
                  </div>

                  {/* 핵심 강점 */}
                  <div className="text-center p-6 bg-white rounded-2xl shadow-lg border border-slate-100">
                    <div className="w-16 h-16 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
                      <Star className="w-8 h-8 text-white" />
                    </div>
                    <h3 className="text-lg font-bold text-slate-800 mb-2">핵심 강점</h3>
                    <p className="text-sm text-slate-600">
                      {data.strengths.length}개 영역에서<br/>
                      경쟁 우위 확보
                    </p>
                  </div>

                  {/* 개선 기회 */}
                  <div className="text-center p-6 bg-white rounded-2xl shadow-lg border border-slate-100">
                    <div className="w-16 h-16 bg-gradient-to-br from-amber-400 to-amber-600 rounded-full flex items-center justify-center mx-auto mb-4">
                      <Lightbulb className="w-8 h-8 text-white" />
                    </div>
                    <h3 className="text-lg font-bold text-slate-800 mb-2">개선 기회</h3>
                    <p className="text-sm text-slate-600">
                      {data.improvements.length}개 영역에서<br/>
                      즉시 개선 가능
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Performance Dashboard */}
            <Card className="border-0 shadow-xl">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <div className="w-10 h-10 bg-gradient-to-br from-purple-500 to-pink-600 rounded-lg flex items-center justify-center">
                      <BarChart3 className="w-5 h-5 text-white" />
                    </div>
                    <h2 className="text-2xl font-bold text-slate-800">성과 대시보드</h2>
                  </div>
                  <Badge className="bg-gradient-to-r from-green-500 to-emerald-600 text-white">
                    업계 상위 15%
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                  {/* 카테고리별 점수 */}
                  <div className="space-y-6">
                    <h3 className="text-lg font-semibold text-slate-800 mb-4">영역별 성과</h3>
                    {Object.entries(data.categoryScores).map(([category, score]) => (
                      <div key={category} className="space-y-3">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center space-x-3">
                            <div className="w-8 h-8 bg-gradient-to-br from-slate-100 to-slate-200 rounded-lg flex items-center justify-center">
                              {categoryIcons[category as keyof typeof categoryIcons]}
                            </div>
                            <span className="font-medium text-slate-700">
                              {categoryNames[category as keyof typeof categoryNames]}
                            </span>
                          </div>
                          <div className="flex items-center space-x-2">
                            <span className="text-lg font-bold text-slate-800">{score.toFixed(1)}</span>
                            <span className="text-sm text-slate-500">/5.0</span>
                          </div>
                        </div>
                        <div className="relative">
                          <Progress 
                            value={(score / 5) * 100} 
                            className="h-3 bg-slate-100"
                          />
                          <div 
                            className="absolute top-0 left-0 h-3 rounded-full bg-gradient-to-r from-blue-500 to-purple-600 transition-all duration-1000"
                            style={{ width: `${(score / 5) * 100}%` }}
                          />
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* 벤치마크 비교 */}
                  <div className="bg-gradient-to-br from-slate-50 to-slate-100 rounded-2xl p-6">
                    <h3 className="text-lg font-semibold text-slate-800 mb-6">벤치마크 비교</h3>
                    
                    <div className="space-y-6">
                      {/* 업계 평균 vs 현재 */}
                      <div className="bg-white rounded-xl p-4 shadow-sm">
                        <div className="flex items-center justify-between mb-3">
                          <span className="text-sm font-medium text-slate-600">업계 평균</span>
                          <span className="text-lg font-bold text-slate-400">65점</span>
                        </div>
                        <div className="flex items-center justify-between">
                          <span className="text-sm font-medium text-slate-800">귀사 점수</span>
                          <span className="text-lg font-bold text-blue-600">{data.overallScore}점</span>
                        </div>
                        <div className="mt-3 flex items-center space-x-2">
                          <TrendingUp className="w-4 h-4 text-green-500" />
                          <span className="text-sm text-green-600 font-medium">
                            +{data.overallScore - 65}점 우위
                          </span>
                        </div>
                      </div>

                      {/* Top Performers */}
                      <div className="bg-white rounded-xl p-4 shadow-sm">
                        <div className="flex items-center justify-between mb-3">
                          <span className="text-sm font-medium text-slate-600">업계 상위 10%</span>
                          <span className="text-lg font-bold text-slate-400">85점</span>
                        </div>
                        <div className="flex items-center justify-between">
                          <span className="text-sm font-medium text-slate-800">목표까지</span>
                          <span className="text-lg font-bold text-amber-600">{85 - data.overallScore}점</span>
                        </div>
                        <div className="mt-3 flex items-center space-x-2">
                          <Target className="w-4 h-4 text-amber-500" />
                          <span className="text-sm text-amber-600 font-medium">
                            달성 가능 목표
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Detailed Analysis */}
        {activeSection === 'detailed-analysis' && (
          <div className="space-y-8">
            {/* 강점 분석 */}
            <Card className="border-0 shadow-xl">
              <CardHeader className="bg-gradient-to-r from-emerald-50 to-emerald-100 rounded-t-lg">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-emerald-700 rounded-lg flex items-center justify-center">
                    <CheckCircle2 className="w-5 h-5 text-white" />
                  </div>
                  <h2 className="text-2xl font-bold text-emerald-800">핵심 강점 분석</h2>
                </div>
              </CardHeader>
              <CardContent className="pt-8">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  {data.strengths.map((strength, index) => (
                    <div key={index} className="bg-gradient-to-br from-white to-emerald-50 rounded-xl p-6 border border-emerald-100">
                      <div className="flex items-start space-x-4">
                        <div className="w-8 h-8 bg-gradient-to-br from-emerald-400 to-emerald-600 rounded-full flex items-center justify-center flex-shrink-0">
                          <span className="text-white font-bold text-sm">{index + 1}</span>
                        </div>
                        <div>
                          <p className="text-slate-800 font-medium leading-relaxed">{strength}</p>
                          <div className="mt-3 flex items-center space-x-2">
                            <Badge className="bg-emerald-100 text-emerald-700 hover:bg-emerald-100">
                              경쟁 우위
                            </Badge>
                            <Badge variant="outline" className="border-emerald-200 text-emerald-600">
                              지속 발전
                            </Badge>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* 개선 영역 */}
            <Card className="border-0 shadow-xl">
              <CardHeader className="bg-gradient-to-r from-amber-50 to-amber-100 rounded-t-lg">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-amber-500 to-amber-700 rounded-lg flex items-center justify-center">
                    <AlertTriangle className="w-5 h-5 text-white" />
                  </div>
                  <h2 className="text-2xl font-bold text-amber-800">개선 기회 영역</h2>
                </div>
              </CardHeader>
              <CardContent className="pt-8">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  {data.improvements.map((improvement, index) => (
                    <div key={index} className="bg-gradient-to-br from-white to-amber-50 rounded-xl p-6 border border-amber-100">
                      <div className="flex items-start space-x-4">
                        <div className="w-8 h-8 bg-gradient-to-br from-amber-400 to-amber-600 rounded-full flex items-center justify-center flex-shrink-0">
                          <span className="text-white font-bold text-sm">{index + 1}</span>
                        </div>
                        <div>
                          <p className="text-slate-800 font-medium leading-relaxed">{improvement}</p>
                          <div className="mt-3 flex items-center space-x-2">
                            <Badge className="bg-amber-100 text-amber-700 hover:bg-amber-100">
                              즉시 개선
                            </Badge>
                            <Badge variant="outline" className="border-amber-200 text-amber-600">
                              높은 효과
                            </Badge>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Strategic Recommendations */}
        {activeSection === 'strategic-recommendations' && (
          <div className="space-y-8">
            <Card className="border-0 shadow-xl">
              <CardHeader className="bg-gradient-to-r from-blue-50 to-purple-100 rounded-t-lg">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
                    <Lightbulb className="w-5 h-5 text-white" />
                  </div>
                  <h2 className="text-2xl font-bold text-slate-800">전략적 권고사항</h2>
                </div>
              </CardHeader>
              <CardContent className="pt-8">
                <div className="space-y-8">
                  {data.recommendations.map((recommendation, index) => (
                    <div key={index} className="bg-gradient-to-br from-white to-slate-50 rounded-2xl p-8 border border-slate-100 shadow-lg">
                      <div className="flex items-start space-x-6">
                        <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-purple-600 rounded-xl flex items-center justify-center flex-shrink-0">
                          <span className="text-white font-bold text-lg">{index + 1}</span>
                        </div>
                        <div className="flex-1">
                          <p className="text-lg text-slate-800 font-medium leading-relaxed mb-4">
                            {recommendation}
                          </p>
                          <div className="flex items-center space-x-4">
                            <Badge className="bg-gradient-to-r from-blue-500 to-purple-600 text-white">
                              전략적 우선순위
                            </Badge>
                            <div className="flex items-center space-x-2 text-sm text-slate-600">
                              <Clock className="w-4 h-4" />
                              <span>3-6개월 내 실행</span>
                            </div>
                            <div className="flex items-center space-x-2 text-sm text-slate-600">
                              <TrendingUp className="w-4 h-4" />
                              <span>높은 ROI 예상</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Implementation Roadmap */}
        {activeSection === 'implementation-roadmap' && (
          <div className="space-y-8">
            <Card className="border-0 shadow-xl">
              <CardHeader className="bg-gradient-to-r from-slate-50 to-slate-100 rounded-t-lg">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-slate-600 to-slate-800 rounded-lg flex items-center justify-center">
                    <Clock className="w-5 h-5 text-white" />
                  </div>
                  <h2 className="text-2xl font-bold text-slate-800">3단계 실행 로드맵</h2>
                </div>
              </CardHeader>
              <CardContent className="pt-8">
                <div className="space-y-8">
                  {/* Phase 1 */}
                  <div className="relative">
                    <div className="flex items-start space-x-6">
                      <div className="w-16 h-16 bg-gradient-to-br from-red-500 to-red-700 rounded-2xl flex items-center justify-center flex-shrink-0 shadow-lg">
                        <span className="text-white font-bold text-xl">1</span>
                      </div>
                      <div className="flex-1 bg-gradient-to-br from-red-50 to-red-100 rounded-2xl p-8 border border-red-200">
                        <div className="flex items-center justify-between mb-4">
                          <h3 className="text-xl font-bold text-red-800">기초 구축 단계</h3>
                          <Badge className="bg-red-100 text-red-700">0-3개월</Badge>
                        </div>
                        <p className="text-red-700 text-lg leading-relaxed">{data.roadmap.phase1}</p>
                        <div className="mt-4 flex items-center space-x-2">
                          <Zap className="w-4 h-4 text-red-600" />
                          <span className="text-sm text-red-600 font-medium">즉시 실행 가능</span>
                        </div>
                      </div>
                    </div>
                    {/* 연결선 */}
                    <div className="absolute left-8 top-16 w-0.5 h-8 bg-gradient-to-b from-red-300 to-orange-300"></div>
                  </div>

                  {/* Phase 2 */}
                  <div className="relative">
                    <div className="flex items-start space-x-6">
                      <div className="w-16 h-16 bg-gradient-to-br from-orange-500 to-orange-700 rounded-2xl flex items-center justify-center flex-shrink-0 shadow-lg">
                        <span className="text-white font-bold text-xl">2</span>
                      </div>
                      <div className="flex-1 bg-gradient-to-br from-orange-50 to-orange-100 rounded-2xl p-8 border border-orange-200">
                        <div className="flex items-center justify-between mb-4">
                          <h3 className="text-xl font-bold text-orange-800">확산 및 통합</h3>
                          <Badge className="bg-orange-100 text-orange-700">4-6개월</Badge>
                        </div>
                        <p className="text-orange-700 text-lg leading-relaxed">{data.roadmap.phase2}</p>
                        <div className="mt-4 flex items-center space-x-2">
                          <Users className="w-4 h-4 text-orange-600" />
                          <span className="text-sm text-orange-600 font-medium">조직 전체 확산</span>
                        </div>
                      </div>
                    </div>
                    {/* 연결선 */}
                    <div className="absolute left-8 top-16 w-0.5 h-8 bg-gradient-to-b from-orange-300 to-blue-300"></div>
                  </div>

                  {/* Phase 3 */}
                  <div>
                    <div className="flex items-start space-x-6">
                      <div className="w-16 h-16 bg-gradient-to-br from-blue-500 to-blue-700 rounded-2xl flex items-center justify-center flex-shrink-0 shadow-lg">
                        <span className="text-white font-bold text-xl">3</span>
                      </div>
                      <div className="flex-1 bg-gradient-to-br from-blue-50 to-blue-100 rounded-2xl p-8 border border-blue-200">
                        <div className="flex items-center justify-between mb-4">
                          <h3 className="text-xl font-bold text-blue-800">고도화 및 최적화</h3>
                          <Badge className="bg-blue-100 text-blue-700">7-12개월</Badge>
                        </div>
                        <p className="text-blue-700 text-lg leading-relaxed">{data.roadmap.phase3}</p>
                        <div className="mt-4 flex items-center space-x-2">
                          <Star className="w-4 h-4 text-blue-600" />
                          <span className="text-sm text-blue-600 font-medium">혁신 리더십 확보</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        )}
      </div>

      {/* 하단 액션 바 */}
      <div className="sticky bottom-0 bg-white/95 backdrop-blur-sm border-t border-slate-200 p-6">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <div className="w-3 h-3 bg-green-500 rounded-full animate-pulse"></div>
              <span className="text-sm text-slate-600">보고서 생성 완료</span>
            </div>
            <span className="text-sm text-slate-400">•</span>
            <span className="text-sm text-slate-600">
              Generated in 0.8 seconds
            </span>
          </div>
          
          <div className="flex items-center space-x-4">
            <Button variant="outline" className="flex items-center space-x-2">
              <Share2 className="w-4 h-4" />
              <span>공유</span>
            </Button>
            <Button className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white flex items-center space-x-2">
              <Download className="w-4 h-4" />
              <span>PDF 다운로드</span>
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};
