'use client';

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  Brain,
  TrendingUp,
  Target,
  AlertTriangle,
  CheckCircle,
  Download,
  Mail,
  BarChart3,
  Users,
  Lightbulb,
  Calendar,
  Award,
  Star,
  Zap,
  Activity,
  Share2
} from 'lucide-react';
import { DiagnosisResult } from '../types';
import { GRADE_CRITERIA } from '../constants/questions';
import { PremiumMcKinseyReport } from '@/components/diagnosis/PremiumMcKinseyReport';
import { AdvancedDataVisualization } from '@/components/diagnosis/AdvancedDataVisualization';

interface DiagnosisResultViewProps {
  result: DiagnosisResult;
}

export const DiagnosisResultView: React.FC<DiagnosisResultViewProps> = ({ result }) => {
  const [activeTab, setActiveTab] = useState('mckinsey-report');
  const [viewMode, setViewMode] = useState<'premium' | 'standard'>('premium');
  const gradeInfo = GRADE_CRITERIA[result.grade as keyof typeof GRADE_CRITERIA];

  // 카테고리 이름 매핑
  const categoryNames = {
    leadership: '경영진 리더십',
    infrastructure: 'AI 인프라',
    employeeCapability: '직원 역량',
    culture: '조직 문화',
    practicalApplication: '실무 적용',
    dataCapability: '데이터 역량'
  };

  // 등급별 색상
  const getGradeColor = (grade: string) => {
    switch(grade) {
      case 'S': return 'bg-gradient-to-r from-purple-600 to-purple-800';
      case 'A': return 'bg-gradient-to-r from-blue-600 to-blue-800';
      case 'B': return 'bg-gradient-to-r from-emerald-600 to-emerald-800';
      case 'C': return 'bg-gradient-to-r from-amber-600 to-amber-800';
      case 'D': return 'bg-gradient-to-r from-orange-600 to-orange-800';
      case 'F': return 'bg-gradient-to-r from-red-600 to-red-800';
      default: return 'bg-gradient-to-r from-gray-600 to-gray-800';
    }
  };

  // 맥킨지 리포트용 데이터 변환
  const mcKinseyData = {
    companyName: result.companyName,
    overallScore: result.totalScore,
    grade: result.grade,
    categoryScores: result.categoryScores,
    recommendations: [
      "AI 기초 인프라 구축을 통한 디지털 전환 가속화",
      "데이터 기반 의사결정 문화 정착 및 조직 역량 강화", 
      "실무진 AI 활용 역량 개발 프로그램 도입",
      "경영진 AI 리더십 강화를 통한 변화 관리"
    ],
    strengths: result.swotAnalysis.strengths,
    improvements: result.swotAnalysis.weaknesses,
    roadmap: {
      phase1: "기초 역량 구축 (1-3개월)",
      phase2: "실무 적용 확산 (4-6개월)", 
      phase3: "고도화 및 최적화 (7-12개월)"
    }
  };

  // 고급 데이터 시각화용 데이터
  const visualizationData = {
    categoryScores: result.categoryScores,
    benchmarkData: {
      industry: result.benchmarkAnalysis.industryAverage,
      topPerformers: 85,
      current: result.totalScore
    },
    trendData: Object.entries(result.categoryScores).map(([category, score]) => ({
      category: categoryNames[category as keyof typeof categoryNames],
      current: score,
      potential: Math.min(5, score + (5 - score) * 0.7),
      gap: Math.max(0, 5 - score)
    }))
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100">
      {/* 프리미엄 헤더 */}
      <div className="bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 text-white">
        <div className="max-w-7xl mx-auto px-6 py-12">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-6">
              <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-4 border border-white/20">
                <Award className="w-12 h-12 text-white" />
              </div>
              <div>
                <div className="flex items-center space-x-3 mb-2">
                  <h1 className="text-4xl font-bold">AI 역량진단 보고서</h1>
                  <Badge className="bg-gradient-to-r from-blue-500 to-purple-600 text-white border-0 text-lg px-4 py-2">
                    McKinsey Style
                  </Badge>
                </div>
                <p className="text-2xl text-slate-300">{result.companyName}</p>
                <p className="text-slate-400 mt-1">
                  Generated by AICAMP • {new Date(result.submittedAt).toLocaleDateString('ko-KR')}
                </p>
              </div>
            </div>
            
            <div className="text-center">
              <div className={`w-32 h-32 rounded-full ${getGradeColor(result.grade)} flex items-center justify-center shadow-2xl border-4 border-white/20`}>
                <span className="text-6xl font-bold text-white">{result.grade}</span>
              </div>
              <p className="text-white mt-4 font-medium text-lg">종합 등급</p>
              <p className="text-slate-300">{result.totalScore}점 / 100점</p>
            </div>
          </div>
        </div>
      </div>

      {/* 뷰 모드 선택 */}
      <div className="sticky top-0 z-50 bg-white/95 backdrop-blur-sm border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Button
                onClick={() => setViewMode('premium')}
                className={`${viewMode === 'premium' 
                  ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white' 
                  : 'bg-white text-slate-600 hover:bg-slate-50'
                } flex items-center space-x-2 px-6 py-3 rounded-lg border shadow-sm transition-all duration-200`}
              >
                <Star className="w-4 h-4" />
                <span className="font-medium">프리미엄 리포트</span>
              </Button>
              <Button
                onClick={() => setViewMode('standard')}
                className={`${viewMode === 'standard' 
                  ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white' 
                  : 'bg-white text-slate-600 hover:bg-slate-50'
                } flex items-center space-x-2 px-6 py-3 rounded-lg border shadow-sm transition-all duration-200`}
              >
                <BarChart3 className="w-4 h-4" />
                <span className="font-medium">표준 리포트</span>
              </Button>
            </div>
            
            <div className="flex items-center space-x-4">
              <Button variant="outline" className="flex items-center space-x-2">
                <Share2 className="w-4 h-4" />
                <span>공유</span>
              </Button>
              <Button className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white flex items-center space-x-2">
                <Download className="w-4 h-4" />
                <span>PDF 다운로드</span>
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* 메인 컨텐츠 */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        {viewMode === 'premium' ? (
          <PremiumMcKinseyReport data={mcKinseyData} />
        ) : (
          <>
            {/* 탭 네비게이션 */}
            <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-8">
              <TabsList className="grid grid-cols-2 lg:grid-cols-7 bg-white shadow-lg rounded-xl p-2">
                <TabsTrigger value="visualization" className="data-[state=active]:bg-gradient-to-r data-[state=active]:from-blue-500 data-[state=active]:to-purple-600 data-[state=active]:text-white">
                  <Activity className="w-4 h-4 mr-2" />
                  데이터 시각화
                </TabsTrigger>
                <TabsTrigger value="overview">
                  <Brain className="w-4 h-4 mr-2" />
                  종합 분석
                </TabsTrigger>
                <TabsTrigger value="scores">
                  <BarChart3 className="w-4 h-4 mr-2" />
                  영역별 점수
                </TabsTrigger>
                <TabsTrigger value="benchmark">
                  <Target className="w-4 h-4 mr-2" />
                  벤치마크
                </TabsTrigger>
                <TabsTrigger value="swot">
                  <TrendingUp className="w-4 h-4 mr-2" />
                  SWOT 분석
                </TabsTrigger>
                <TabsTrigger value="strategy">
                  <Lightbulb className="w-4 h-4 mr-2" />
                  전략 제안
                </TabsTrigger>
                <TabsTrigger value="roadmap">
                  <Calendar className="w-4 h-4 mr-2" />
                  실행 로드맵
                </TabsTrigger>
              </TabsList>

              {/* 고급 데이터 시각화 탭 */}
              <TabsContent value="visualization">
                <AdvancedDataVisualization data={visualizationData} />
              </TabsContent>

        {/* 종합 분석 탭 */}
        <TabsContent value="overview" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Brain className="w-5 h-5" />
                종합 진단 의견
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Alert>
                <AlertDescription>
                  {result.companyName}의 AI 역량은 <strong>{gradeInfo?.label}</strong> 수준으로 평가됩니다.
                  현재 종합 점수는 {result.totalScore}점으로, 업계 평균({result.benchmarkAnalysis.industryAverage}점) 
                  {result.benchmarkAnalysis.gap > 0 ? '을 상회' : '에 미달'}하고 있습니다.
                </AlertDescription>
              </Alert>

              <div className="mt-6 space-y-4">
                <div>
                  <h3 className="font-semibold mb-2">핵심 강점</h3>
                  <ul className="space-y-2">
                    {result.swotAnalysis.strengths.slice(0, 3).map((strength, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <CheckCircle className="w-4 h-4 text-green-500 mt-0.5" />
                        <span className="text-sm">{strength}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">우선 개선 영역</h3>
                  <ul className="space-y-2">
                    {result.swotAnalysis.weaknesses.slice(0, 3).map((weakness, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <AlertTriangle className="w-4 h-4 text-yellow-500 mt-0.5" />
                        <span className="text-sm">{weakness}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* AI 고몰입 조직 구축 방안 */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Users className="w-5 h-5" />
                AI 고몰입 조직 구축 방안
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold mb-2">비전</h3>
                  <p className="text-sm text-gray-700">{result.highEngagementPlan.vision}</p>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">핵심 가치</h3>
                  <div className="flex flex-wrap gap-2">
                    {result.highEngagementPlan.coreValues.map((value, idx) => (
                      <Badge key={idx} variant="secondary">{value}</Badge>
                    ))}
                  </div>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">주요 이니셔티브</h3>
                  <div className="space-y-3">
                    {result.highEngagementPlan.keyInitiatives.slice(0, 3).map((initiative, idx) => (
                      <div key={idx} className="border-l-2 border-blue-500 pl-4">
                        <h4 className="font-medium">{initiative.name}</h4>
                        <p className="text-sm text-gray-600">{initiative.objective}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* 영역별 점수 탭 */}
        <TabsContent value="scores" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>영역별 AI 역량 점수</CardTitle>
              <CardDescription>6개 핵심 영역의 상세 평가 결과</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                {Object.entries(result.categoryScores).map(([category, score]) => (
                  <div key={category}>
                    <div className="flex justify-between items-center mb-2">
                      <span className="font-medium">{categoryNames[category as keyof typeof categoryNames]}</span>
                      <span className="text-sm font-semibold">{score}점</span>
                    </div>
                    <Progress value={score} className="h-3" />
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* 벤치마크 탭 */}
        <TabsContent value="benchmark" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BarChart3 className="w-5 h-5" />
                업계 벤치마크 비교
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                  <div>
                    <p className="font-medium">귀사 점수</p>
                    <p className="text-2xl font-bold">{result.totalScore}점</p>
                  </div>
                  <div className="text-center">
                    <p className="text-sm text-gray-600">GAP</p>
                    <p className="text-xl font-bold text-blue-600">
                      {result.benchmarkAnalysis.gap > 0 ? '+' : ''}{result.benchmarkAnalysis.gap}점
                    </p>
                  </div>
                  <div>
                    <p className="font-medium">업계 평균</p>
                    <p className="text-2xl font-bold">{result.benchmarkAnalysis.industryAverage}점</p>
                  </div>
                </div>

                <Alert>
                  <Lightbulb className="w-4 h-4" />
                  <AlertDescription>
                    귀사는 동종 업계 대비 상위 {result.benchmarkAnalysis.percentile}%에 위치하고 있으며,
                    {result.benchmarkAnalysis.competitivePosition} 수준의 경쟁력을 보유하고 있습니다.
                  </AlertDescription>
                </Alert>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* SWOT 분석 탭 */}
        <TabsContent value="swot" className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card>
              <CardHeader className="bg-blue-50">
                <CardTitle className="text-blue-900">강점 (Strengths)</CardTitle>
              </CardHeader>
              <CardContent className="pt-6">
                <ul className="space-y-2">
                  {result.swotAnalysis.strengths.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <CheckCircle className="w-4 h-4 text-blue-600 mt-0.5" />
                      <span className="text-sm">{item}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="bg-yellow-50">
                <CardTitle className="text-yellow-900">약점 (Weaknesses)</CardTitle>
              </CardHeader>
              <CardContent className="pt-6">
                <ul className="space-y-2">
                  {result.swotAnalysis.weaknesses.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <AlertTriangle className="w-4 h-4 text-yellow-600 mt-0.5" />
                      <span className="text-sm">{item}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="bg-green-50">
                <CardTitle className="text-green-900">기회 (Opportunities)</CardTitle>
              </CardHeader>
              <CardContent className="pt-6">
                <ul className="space-y-2">
                  {result.swotAnalysis.opportunities.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <TrendingUp className="w-4 h-4 text-green-600 mt-0.5" />
                      <span className="text-sm">{item}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="bg-red-50">
                <CardTitle className="text-red-900">위협 (Threats)</CardTitle>
              </CardHeader>
              <CardContent className="pt-6">
                <ul className="space-y-2">
                  {result.swotAnalysis.threats.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <AlertTriangle className="w-4 h-4 text-red-600 mt-0.5" />
                      <span className="text-sm">{item}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* 전략 제안 탭 */}
        <TabsContent value="strategy" className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">SO 전략 (강점-기회)</CardTitle>
                <CardDescription>강점을 활용한 기회 포착 전략</CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {result.strategies.SO.map((strategy, idx) => (
                    <li key={idx} className="text-sm">• {strategy}</li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-lg">WO 전략 (약점-기회)</CardTitle>
                <CardDescription>약점 보완을 통한 기회 활용 전략</CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {result.strategies.WO.map((strategy, idx) => (
                    <li key={idx} className="text-sm">• {strategy}</li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-lg">ST 전략 (강점-위협)</CardTitle>
                <CardDescription>강점을 활용한 위협 대응 전략</CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {result.strategies.ST.map((strategy, idx) => (
                    <li key={idx} className="text-sm">• {strategy}</li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-lg">WT 전략 (약점-위협)</CardTitle>
                <CardDescription>약점 보완 및 위협 방어 전략</CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {result.strategies.WT.map((strategy, idx) => (
                    <li key={idx} className="text-sm">• {strategy}</li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* 실행 로드맵 탭 */}
        <TabsContent value="roadmap" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Calendar className="w-5 h-5" />
                단계별 실행 로드맵
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-8">
                {/* 즉시 실행 (0-3개월) */}
                <div>
                  <h3 className="font-semibold text-lg mb-4 text-red-600">즉시 실행 (0-3개월)</h3>
                  <div className="space-y-3">
                    {result.roadmap.immediate.map((item, idx) => (
                      <div key={idx} className="border-l-4 border-red-500 pl-4">
                        <div className="flex items-center gap-2 mb-1">
                          <h4 className="font-medium">{item.title}</h4>
                          <Badge variant={item.priority === 'high' ? 'destructive' : 'secondary'}>
                            {item.priority === 'high' ? '높음' : item.priority === 'medium' ? '중간' : '낮음'}
                          </Badge>
                        </div>
                        <p className="text-sm text-gray-600">{item.description}</p>
                        <p className="text-xs text-gray-500 mt-1">예상 기간: {item.estimatedDuration}</p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* 단기 목표 (3-6개월) */}
                <div>
                  <h3 className="font-semibold text-lg mb-4 text-orange-600">단기 목표 (3-6개월)</h3>
                  <div className="space-y-3">
                    {result.roadmap.shortTerm.map((item, idx) => (
                      <div key={idx} className="border-l-4 border-orange-500 pl-4">
                        <div className="flex items-center gap-2 mb-1">
                          <h4 className="font-medium">{item.title}</h4>
                          <Badge variant={item.priority === 'high' ? 'destructive' : 'secondary'}>
                            {item.priority === 'high' ? '높음' : item.priority === 'medium' ? '중간' : '낮음'}
                          </Badge>
                        </div>
                        <p className="text-sm text-gray-600">{item.description}</p>
                        <p className="text-xs text-gray-500 mt-1">예상 기간: {item.estimatedDuration}</p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* 중기 전략 (6-12개월) */}
                <div>
                  <h3 className="font-semibold text-lg mb-4 text-blue-600">중기 전략 (6-12개월)</h3>
                  <div className="space-y-3">
                    {result.roadmap.midTerm.map((item, idx) => (
                      <div key={idx} className="border-l-4 border-blue-500 pl-4">
                        <div className="flex items-center gap-2 mb-1">
                          <h4 className="font-medium">{item.title}</h4>
                          <Badge variant={item.priority === 'high' ? 'destructive' : 'secondary'}>
                            {item.priority === 'high' ? '높음' : item.priority === 'medium' ? '중간' : '낮음'}
                          </Badge>
                        </div>
                        <p className="text-sm text-gray-600">{item.description}</p>
                        <p className="text-xs text-gray-500 mt-1">예상 기간: {item.estimatedDuration}</p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* 장기 비전 (1년 이상) */}
                <div>
                  <h3 className="font-semibold text-lg mb-4 text-green-600">장기 비전 (1년 이상)</h3>
                  <div className="space-y-3">
                    {result.roadmap.longTerm.map((item, idx) => (
                      <div key={idx} className="border-l-4 border-green-500 pl-4">
                        <div className="flex items-center gap-2 mb-1">
                          <h4 className="font-medium">{item.title}</h4>
                          <Badge variant={item.priority === 'high' ? 'destructive' : 'secondary'}>
                            {item.priority === 'high' ? '높음' : item.priority === 'medium' ? '중간' : '낮음'}
                          </Badge>
                        </div>
                        <p className="text-sm text-gray-600">{item.description}</p>
                        <p className="text-xs text-gray-500 mt-1">예상 기간: {item.estimatedDuration}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* 추천 교육과정 */}
          <Card>
            <CardHeader>
              <CardTitle>AICAMP 추천 교육과정</CardTitle>
              <CardDescription>귀사의 AI 역량 강화를 위한 맞춤형 교육 프로그램</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {result.recommendedPrograms.map((program, idx) => (
                  <div key={idx} className="border rounded-lg p-4">
                    <div className="flex justify-between items-start mb-2">
                      <h4 className="font-medium">{program.name}</h4>
                      <Badge>{program.level}</Badge>
                    </div>
                    <p className="text-sm text-gray-600 mb-2">{program.description}</p>
                    <div className="flex justify-between text-xs text-gray-500">
                      <span>{program.category}</span>
                      <span>{program.duration}</span>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

              {/* 하단 액션 버튼 */}
              <Card className="border-0 shadow-xl bg-gradient-to-r from-slate-50 to-blue-50">
                <CardContent className="pt-8 pb-8">
                  <div className="text-center space-y-6">
                    <div>
                      <h3 className="text-2xl font-bold text-slate-800 mb-2">다음 단계</h3>
                      <p className="text-slate-600">AI 역량 강화를 위한 전문가 지원을 받아보세요</p>
                    </div>
                    <div className="flex flex-wrap gap-4 justify-center">
                      <Button className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white px-8 py-3 text-lg flex items-center gap-2 shadow-lg">
                        <Download className="w-5 h-5" />
                        프리미엄 보고서 다운로드
                      </Button>
                      <Button variant="outline" className="px-8 py-3 text-lg flex items-center gap-2 border-2 border-blue-200 hover:bg-blue-50">
                        <Mail className="w-5 h-5" />
                        이메일로 전송
                      </Button>
                      <Button variant="outline" className="px-8 py-3 text-lg border-2 border-emerald-200 hover:bg-emerald-50 text-emerald-700">
                        <Users className="w-5 h-5 mr-2" />
                        전문가 상담 신청
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </Tabs>
          </>
        )}
      </div>
    </div>
  );
};